const ADD_ADDRESS_BOOK_ENTRY = 'app/addressBook/ADD';
const EDIT_ADDRESS_BOOK_ENTRY = 'app/addressBook/EDIT';

const DELETE_ADDRESS_BOOK_ENTRY = 'app/addressBook/DELETE';
const LOAD_ADDRESS_BOOK_ENTRIES = 'app/addressBook/LOAD';

const SET_ADDRESS_BOOK_LABEL_ERROR = 'app/addressBook/LABEL/ERROR';
const SET_ADDRESS_BOOK_ADDRESS_ERROR = 'app/addressBook/ADDRESS/ERROR';

export {
	ADD_ADDRESS_BOOK_ENTRY,
	EDIT_ADDRESS_BOOK_ENTRY,
	LOAD_ADDRESS_BOOK_ENTRIES,
	DELETE_ADDRESS_BOOK_ENTRY,
	SET_ADDRESS_BOOK_LABEL_ERROR,
	SET_ADDRESS_BOOK_ADDRESS_ERROR
};
