const ADRESS_BOOK_ENTRY_ADD = 'app/addressBook/ADD';
const ADDRESS_BOOK_ENTRY_EDIT = 'app/addressBook/EDIT';

const ADDRESS_BOOK_ENTRY_DELETE = 'app/addressBook/DELETE';
const ADDRESS_BOOK_ENTRIES_LOAD = 'app/addressBook/LOAD';

const ADDRESS_BOOK_LABEL_ERROR_SET = 'app/addressBook/LABEL/ERROR';
const ADDRESS_BOOK_ADDRESS_ERROR_SET = 'app/addressBook/ADDRESS/ERROR';

export {
	ADRESS_BOOK_ENTRY_ADD,
	ADDRESS_BOOK_ENTRY_EDIT,
	ADDRESS_BOOK_ENTRIES_LOAD,
	ADDRESS_BOOK_ENTRY_DELETE,
	ADDRESS_BOOK_LABEL_ERROR_SET,
	ADDRESS_BOOK_ADDRESS_ERROR_SET
};
