/* istanbul ignore file */
const WALLET_UPDATE = 'app/wallet/UPDATE';
const WALLET_AVATAR_UPDATE = 'app/wallet/avatar/UPDATE';
const WALLET_NAME_UPDATE = 'app/wallet/name/UPDATE';
const WALLET_SETUP_UPDATE = 'app/wallet/setup/UPDATE';
const WALLET_DID_CREATE = 'app/wallet/did/CREATE';
const WALLET_DID_UPDATE = 'app/wallet/did/UPDATE';
const WALLET_ASSOCIATE_DID_ERROR_SET = 'app/wallet/did/ASSOCIATE/ERROR';
const WALLET_DID_ORIGIN_URL_SET = 'app/wallet/did/ORIGIN_Url/SET';
const WALLET_START_DID_FLOW = 'app/wallet/CREATE_DID_FLOW/START';
const WALLET_START_ASSOCIATE_DID_FLOW = 'app/wallet/ASSOCIATE_DID_FLOW/START';

export {
	WALLET_UPDATE,
	WALLET_AVATAR_UPDATE,
	WALLET_NAME_UPDATE,
	WALLET_SETUP_UPDATE,
	WALLET_DID_CREATE,
	WALLET_DID_UPDATE,
	WALLET_ASSOCIATE_DID_ERROR_SET,
	WALLET_DID_ORIGIN_URL_SET,
	WALLET_START_DID_FLOW,
	WALLET_START_ASSOCIATE_DID_FLOW
};
