const INCORPORATIONS_DATA_LOADED = 'app/incorporations/DATA_LOADED';
const INCORPORATIONS_OPEN_DETAILS = 'app/incorporations/OPEN_DETAILS';

export { INCORPORATIONS_DATA_LOADED, INCORPORATIONS_OPEN_DETAILS };
