const APPLICATION_REJECTED = 3;
const APPLICATION_CANCELLED = 8;
const APPLICATION_APPROVED = 2;
const APPLICATION_UPLOAD_REQUIRED = 11;
const APPLICATION_ANSWER_REQUIRED = 9;

export {
	APPLICATION_REJECTED,
	APPLICATION_CANCELLED,
	APPLICATION_APPROVED,
	APPLICATION_UPLOAD_REQUIRED,
	APPLICATION_ANSWER_REQUIRED
};
