import React from 'react';
import { action } from '@storybook/addon-actions';
import { storiesOf } from '@storybook/react';
import { CreateAttribute } from '../src/renderer/attributes/create-attribute';
import { EditAttribute } from '../src/renderer/attributes/edit-attribute';
import { DeleteAttribute } from '../src/renderer/attributes/delete-attribute';
import ListAttributeChooser from '../src/renderer/attributes/choosers/list-attribute-chooser';

storiesOf('Attributes/CreateAttribute', module).add('default', () => (
	<CreateAttribute
		onSave={action('save')}
		onCancel={action('cancel')}
		uiSchemas={[]}
		isDocument={false}
		types={[]}
		open={true}
		text={'Create Attribute'}
		subtitle={'subtitle'}
		typeId=""
	/>
));

storiesOf('Attributes/EditAttribute', module).add('default', () => (
	<EditAttribute
		onSave={action('save')}
		onCancel={action('cancel')}
		uiSchema={{}}
		attribute={{
			id: 1,
			type: { content: { title: 'hi' } },
			data: {},
			documents: [],
			name: 'test'
		}}
		types={[]}
		open={true}
		text={'Create Attribute'}
		subtitle={'subtitle'}
		typeId=""
	/>
));

storiesOf('Attributes/DeleteAttribute', module).add('default', () => (
	<DeleteAttribute
		onConfirm={action('confirm')}
		onCancel={action('cancel')}
		attribute={{
			id: 1,
			type: { content: { title: 'hi' } },
			data: {},
			documents: [],
			name: 'test'
		}}
		open={true}
		text={'Create Attribute'}
	/>
));

const attributes = [
	{
		id: 1,
		name: 'Test Address',
		identityId: 1,
		typeId: 1,
		data: {
			address_line1: 'Test Address line1',
			address_line2: 'Test address line2',
			city: 'Testville',
			province: 'Test Province',
			postalcode: '23123'
		}
	},
	{
		id: 2,
		name: 'Vacation Address',
		identityId: 1,
		typeId: 1,
		data: {
			address_line1: 'Vacation address line1',
			address_line2: 'Vacation address line2',
			city: 'Vacationville',
			province: 'Vacation Province',
			postalcode: '15154132'
		}
	},
	{
		id: 3,
		name: 'USA',
		identityId: 1,
		typeId: 2,
		data: {
			country: 'US'
		}
	}
];

const typesByTypeId = {
	1: {
		url: 'http://platform.selfkey.org/schema/attribute/physical-address.json'
	},
	2: {
		url: 'http://platform.selfkey.org/schema/attribute/country-of-residency.json',
		content: {
			$id: 'http://platform.selfkey.org/schema/attribute/country-of-residency.json',
			$schema: 'http://platform.selfkey.org/schema/identity-attribute.json',
			identityAttribute: true,
			identityAttributeRepository: 'http://platform.selfkey.org/repository.json',
			entityType: ['individual'],
			title: 'Country of Residency',
			description: 'Please specify the country you are currently living in.',
			type: 'object',
			properties: {
				country: {
					$id: 'http://platform.selfkey.org/schema/misc/country.json',
					$schema: 'http://json-schema.org/draft-07/schema',
					title: 'Country',
					type: 'string',
					enum: [
						'AF',
						'AX',
						'AL',
						'DZ',
						'AS',
						'AD',
						'AO',
						'AI',
						'AQ',
						'AG',
						'AR',
						'AM',
						'AW',
						'AU',
						'AT',
						'AZ',
						'BS',
						'BH',
						'BD',
						'BB',
						'BY',
						'BE',
						'BZ',
						'BJ',
						'BM',
						'BT',
						'BO',
						'BQ',
						'BA',
						'BW',
						'BV',
						'BR',
						'IO',
						'BN',
						'BG',
						'BF',
						'BI',
						'KH',
						'CM',
						'CA',
						'CV',
						'KY',
						'CF',
						'TD',
						'CL',
						'CN',
						'CX',
						'CC',
						'CO',
						'KM',
						'CG',
						'CD',
						'CK',
						'CR',
						'CI',
						'HR',
						'CU',
						'CW',
						'CY',
						'CZ',
						'DK',
						'DJ',
						'DM',
						'DO',
						'EC',
						'EG',
						'SV',
						'GQ',
						'ER',
						'EE',
						'ET',
						'FK',
						'FO',
						'FJ',
						'FI',
						'FR',
						'GF',
						'PF',
						'TF',
						'GA',
						'GM',
						'GE',
						'DE',
						'GH',
						'GI',
						'GR',
						'GL',
						'GD',
						'GP',
						'GU',
						'GT',
						'GG',
						'GN',
						'GW',
						'GY',
						'HT',
						'HM',
						'VA',
						'HN',
						'HK',
						'HU',
						'IS',
						'IN',
						'ID',
						'IR',
						'IQ',
						'IE',
						'IM',
						'IL',
						'IT',
						'JM',
						'JP',
						'JE',
						'JO',
						'KZ',
						'KE',
						'KI',
						'KP',
						'KR',
						'KW',
						'KG',
						'LA',
						'LV',
						'LB',
						'LS',
						'LR',
						'LY',
						'LI',
						'LT',
						'LU',
						'MO',
						'MK',
						'MG',
						'MW',
						'MY',
						'MV',
						'ML',
						'MT',
						'MH',
						'MQ',
						'MR',
						'MU',
						'YT',
						'MX',
						'FM',
						'MD',
						'MC',
						'MN',
						'ME',
						'MS',
						'MA',
						'MZ',
						'MM',
						'NA',
						'NR',
						'NP',
						'NL',
						'NC',
						'NZ',
						'NI',
						'NE',
						'NG',
						'NU',
						'NF',
						'MP',
						'NO',
						'OM',
						'PK',
						'PW',
						'PS',
						'PA',
						'PG',
						'PY',
						'PE',
						'PH',
						'PN',
						'PL',
						'PT',
						'PR',
						'QA',
						'RE',
						'RO',
						'RU',
						'RW',
						'BL',
						'SH',
						'KN',
						'LC',
						'MF',
						'PM',
						'VC',
						'WS',
						'SM',
						'ST',
						'SA',
						'SN',
						'RS',
						'SC',
						'SL',
						'SG',
						'SX',
						'SK',
						'SI',
						'SB',
						'SO',
						'ZA',
						'GS',
						'SS',
						'ES',
						'LK',
						'SD',
						'SR',
						'SJ',
						'SZ',
						'SE',
						'CH',
						'SY',
						'TW',
						'TJ',
						'TZ',
						'TH',
						'TL',
						'TG',
						'TK',
						'TO',
						'TT',
						'TN',
						'TR',
						'TM',
						'TC',
						'TV',
						'UG',
						'UA',
						'AE',
						'GB',
						'US',
						'UM',
						'UY',
						'UZ',
						'VU',
						'VE',
						'VN',
						'VG',
						'VI',
						'WF',
						'EH',
						'YE',
						'ZM',
						'ZW'
					],
					enumNames: [
						'Afghanistan',
						'Åland Islands',
						'Albania',
						'Algeria',
						'American Samoa',
						'Andorra',
						'Angola',
						'Anguilla',
						'Antarctica',
						'Antigua and Barbuda',
						'Argentina',
						'Armenia',
						'Aruba',
						'Australia',
						'Austria',
						'Azerbaijan',
						'Bahamas',
						'Bahrain',
						'Bangladesh',
						'Barbados',
						'Belarus',
						'Belgium',
						'Belize',
						'Benin',
						'Bermuda',
						'Bhutan',
						'Bolivia, Plurinational State of',
						'Bonaire, Sint Eustatius and Saba',
						'Bosnia and Herzegovina',
						'Botswana',
						'Bouvet Island',
						'Brazil',
						'British Indian Ocean Territory',
						'Brunei Darussalam',
						'Bulgaria',
						'Burkina Faso',
						'Burundi',
						'Cambodia',
						'Cameroon',
						'Canada',
						'Cape Verde',
						'Cayman Islands',
						'Central African Republic',
						'Chad',
						'Chile',
						'China',
						'Christmas Island',
						'Cocos (Keeling) Islands',
						'Colombia',
						'Comoros',
						'Congo',
						'Congo, the Democratic Republic of the',
						'Cook Islands',
						'Costa Rica',
						"Côte d'Ivoire",
						'Croatia',
						'Cuba',
						'Curaçao',
						'Cyprus',
						'Czech Republic',
						'Denmark',
						'Djibouti',
						'Dominica',
						'Dominican Republic',
						'Ecuador',
						'Egypt',
						'El Salvador',
						'Equatorial Guinea',
						'Eritrea',
						'Estonia',
						'Ethiopia',
						'Falkland Islands (Malvinas)',
						'Faroe Islands',
						'Fiji',
						'Finland',
						'France',
						'French Guiana',
						'French Polynesia',
						'French Southern Territories',
						'Gabon',
						'Gambia',
						'Georgia',
						'Germany',
						'Ghana',
						'Gibraltar',
						'Greece',
						'Greenland',
						'Grenada',
						'Guadeloupe',
						'Guam',
						'Guatemala',
						'Guernsey',
						'Guinea',
						'Guinea-Bissau',
						'Guyana',
						'Haiti',
						'Heard Island and McDonald Islands',
						'Holy See (Vatican City State)',
						'Honduras',
						'Hong Kong',
						'Hungary',
						'Iceland',
						'India',
						'Indonesia',
						'Iran, Islamic Republic of',
						'Iraq',
						'Ireland',
						'Isle of Man',
						'Israel',
						'Italy',
						'Jamaica',
						'Japan',
						'Jersey',
						'Jordan',
						'Kazakhstan',
						'Kenya',
						'Kiribati',
						"Korea, Democratic People's Republic of",
						'Korea, Republic of',
						'Kuwait',
						'Kyrgyzstan',
						"Lao People's Democratic Republic",
						'Latvia',
						'Lebanon',
						'Lesotho',
						'Liberia',
						'Libya',
						'Liechtenstein',
						'Lithuania',
						'Luxembourg',
						'Macao',
						'Macedonia, the Former Yugoslav Republic of',
						'Madagascar',
						'Malawi',
						'Malaysia',
						'Maldives',
						'Mali',
						'Malta',
						'Marshall Islands',
						'Martinique',
						'Mauritania',
						'Mauritius',
						'Mayotte',
						'Mexico',
						'Micronesia, Federated States of',
						'Moldova, Republic of',
						'Monaco',
						'Mongolia',
						'Montenegro',
						'Montserrat',
						'Morocco',
						'Mozambique',
						'Myanmar',
						'Namibia',
						'Nauru',
						'Nepal',
						'Netherlands',
						'New Caledonia',
						'New Zealand',
						'Nicaragua',
						'Niger',
						'Nigeria',
						'Niue',
						'Norfolk Island',
						'Northern Mariana Islands',
						'Norway',
						'Oman',
						'Pakistan',
						'Palau',
						'Palestine, State of',
						'Panama',
						'Papua New Guinea',
						'Paraguay',
						'Peru',
						'Philippines',
						'Pitcairn',
						'Poland',
						'Portugal',
						'Puerto Rico',
						'Qatar',
						'Réunion',
						'Romania',
						'Russian Federation',
						'Rwanda',
						'Saint Barthélemy',
						'Saint Helena, Ascension and Tristan da Cunha',
						'Saint Kitts and Nevis',
						'Saint Lucia',
						'Saint Martin (French part)',
						'Saint Pierre and Miquelon',
						'Saint Vincent and the Grenadines',
						'Samoa',
						'San Marino',
						'Sao Tome and Principe',
						'Saudi Arabia',
						'Senegal',
						'Serbia',
						'Seychelles',
						'Sierra Leone',
						'Singapore',
						'Sint Maarten (Dutch part)',
						'Slovakia',
						'Slovenia',
						'Solomon Islands',
						'Somalia',
						'South Africa',
						'South Georgia and the South Sandwich Islands',
						'South Sudan',
						'Spain',
						'Sri Lanka',
						'Sudan',
						'Suriname',
						'Svalbard and Jan Mayen',
						'Swaziland',
						'Sweden',
						'Switzerland',
						'Syrian Arab Republic',
						'Taiwan, Province of China',
						'Tajikistan',
						'Tanzania, United Republic of',
						'Thailand',
						'Timor-Leste',
						'Togo',
						'Tokelau',
						'Tonga',
						'Trinidad and Tobago',
						'Tunisia',
						'Turkey',
						'Turkmenistan',
						'Turks and Caicos Islands',
						'Tuvalu',
						'Uganda',
						'Ukraine',
						'United Arab Emirates',
						'United Kingdom',
						'United States',
						'United States Minor Outlying Islands',
						'Uruguay',
						'Uzbekistan',
						'Vanuatu',
						'Venezuela, Bolivarian Republic of',
						'Viet Nam',
						'Virgin Islands, British',
						'Virgin Islands, U.S.',
						'Wallis and Futuna',
						'Western Sahara',
						'Yemen',
						'Zambia',
						'Zimbabwe'
					]
				}
			},
			required: ['country']
		}
	}
};

storiesOf('Attributes/ListAttributeChooser', module).add('default', () => (
	<ListAttributeChooser
		selected={1}
		attributes={attributes}
		typesByTypeId={typesByTypeId}
		onSelectOption={action('select')}
		onEditAttribute={action('edit')}
		onAddAttribute={action('add')}
	/>
));
