export const bankingOffers = [
	{
		id: 1,
		countryCode: 'hk',
		region: 'Hong Kong',
		eligibility: 'Resident Individuals,  Regional Individuals, International Individuals',
		minDeposit: 1000,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: false,
		price: 500,
		type: 'personal'
	},
	{
		id: 2,
		countryCode: 'sg',
		region: 'Singapore',
		eligibility: 'Resident Individuals,  Regional Individuals',
		minDeposit: 500,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Credit Cards'],
		personalVisit: true,
		price: 1500,
		type: 'personal'
	},
	{
		id: 3,
		countryCode: 'ky',
		region: 'Cayman',
		eligibility: 'Regional Individuals, International Individuals',
		minDeposit: 1000,
		minDepositCurrency: 'USD',
		goodFor: ['Savings', 'Credit Cards', 'Multi-currency Cards'],
		personalVisit: false,
		price: 800,
		type: 'personal'
	},
	{
		id: 4,
		countryCode: 'vg',
		region: 'British Virgin Islands',
		eligibility: 'Resident Individuals,  Regional Individuals, International Individuals',
		minDeposit: 10000,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: true,
		price: 3500,
		type: 'personal'
	},
	{
		id: 5,
		countryCode: 'kn',
		region: 'Nevis',
		eligibility: 'Resident Individuals,  Regional Individuals',
		minDeposit: 800,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: false,
		price: 200,
		type: 'personal'
	},

	{
		id: 6,
		countryCode: 'hk',
		region: 'Hong Kong',
		eligibility: 'Resident Individuals,  Regional Individuals, International Individuals',
		minDeposit: 1000,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: false,
		price: 500,
		type: 'corporate'
	},
	{
		id: 7,
		countryCode: 'sg',
		region: 'Singapore',
		eligibility: 'Resident Individuals,  Regional Individuals',
		minDeposit: 500,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Credit Cards'],
		personalVisit: true,
		price: 1500,
		type: 'corporate'
	},
	{
		id: 8,
		countryCode: 'ky',
		region: 'Cayman',
		eligibility: 'Regional Individuals, International Individuals',
		minDeposit: 1000,
		minDepositCurrency: 'USD',
		goodFor: ['Savings', 'Credit Cards', 'Multi-currency Cards'],
		personalVisit: false,
		price: 800,
		type: 'corporate'
	},
	{
		id: 9,
		countryCode: 'vg',
		region: 'British Virgin Islands',
		eligibility: 'Resident Individuals,  Regional Individuals, International Individuals',
		minDeposit: 10000,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: true,
		price: 3500,
		type: 'corporate'
	},
	{
		id: 10,
		countryCode: 'kn',
		region: 'Nevis',
		eligibility: 'Resident Individuals,  Regional Individuals',
		minDeposit: 800,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: false,
		price: 200,
		type: 'corporate'
	},

	{
		id: 11,
		countryCode: 'hk',
		region: 'Hong Kong',
		eligibility: 'Resident Individuals,  Regional Individuals, International Individuals',
		minDeposit: 1000,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: false,
		price: 500,
		type: 'private'
	},
	{
		id: 12,
		countryCode: 'sg',
		region: 'Singapore',
		eligibility: 'Resident Individuals,  Regional Individuals',
		minDeposit: 500,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Credit Cards'],
		personalVisit: true,
		price: 1500,
		type: 'private'
	},
	{
		id: 13,
		countryCode: 'ky',
		region: 'Cayman',
		eligibility: 'Regional Individuals, International Individuals',
		minDeposit: 1000,
		minDepositCurrency: 'USD',
		goodFor: ['Savings', 'Credit Cards', 'Multi-currency Cards'],
		personalVisit: false,
		price: 800,
		type: 'private'
	},
	{
		id: 14,
		countryCode: 'vg',
		region: 'British Virgin Islands',
		eligibility: 'Resident Individuals,  Regional Individuals, International Individuals',
		minDeposit: 10000,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: true,
		price: 3500,
		type: 'private'
	},
	{
		id: 15,
		countryCode: 'kn',
		region: 'Nevis',
		eligibility: 'Resident Individuals,  Regional Individuals',
		minDeposit: 800,
		minDepositCurrency: 'USD',
		goodFor: ['Transactional Banking', 'Multi-currency Cards'],
		personalVisit: false,
		price: 200,
		type: 'private'
	}
];
